### ISSUE TITLE
oghliner declines to offline my 4MB CSV file

### ISSUE THREAD

**Issue by wfwalker** [mozilla/oghliner#125] opened 2015-11-01 00:47 UTC
oghliner declines to offline my 4MB CSV file in http://wfwalker.github.io/ebird-mybird/

How can I reconfigure this to allow larger files?

[17:46:35] Skipping static resource "dist/data/ebird.csv" (4.41 MB) - max size is 2.1 MB

**Comment by marco-c** [comment] 2015-11-01 12:59
Duplicate of #28.

**Closed as completed by marco-c** 2015-11-01 12:59 UTC
Labels: duplicate

**Comment by marco-c** [comment] 2015-11-02 11:05
#127 will fix this problem.
