### ISSUE TITLE
Consider the ability to customise the upgrade alert

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/oghliner#242] opened 2015-12-21 23:45 UTC
It would be nice to be able to specify a way to extend or change how the upgrade behaviour happens.

For example we don't really want to intrude on the user to upgrade all of our tabs if they have multiple open.

Perhaps the ability to somehow specify a method to override the confirm behaviour would be enough to manage this.

**Comment by marco-c** [comment] 2015-12-22 14:46
Duplicate of #5.

**Closed as completed by marco-c** 2015-12-22 14:46 UTC
Labels: duplicate
