### ISSUE TITLE
two "CLI interface, oghliner as a template" tests fail

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#183] opened 2015-11-12 21:54 UTC
@marco-c Since #168 two tests are failing on builds (although not all jobs):

>  54 passing (4m)
>  2 failing
>  1) CLI interface, oghliner as a template should work:
>     Error: the number 1 was thrown, throw an Error :)
>      at lib$es6$promise$$internal$$tryCatch (node_modules/sw-precache/node_modules/es6-promise/dist/es6-promise.js:326:16)
>      at lib$es6$promise$$internal$$invokeCallback (node_modules/sw-precache/node_modules/es6-promise/dist/es6-promise.js:338:17)
>      at lib$es6$promise$$internal$$publish (node_modules/sw-precache/node_modules/es6-promise/dist/es6-promise.js:309:11)
>      at lib$es6$promise$$internal$$publishRejection (node_modules/sw-precache/node_modules/es6-promise/dist/es6-promise.js:259:7)
>      at lib$es6$promise$asap$$flush (node_modules/sw-precache/node_modules/es6-promise/dist/es6-promise.js:120:9)
>  2) CLI interface, oghliner as a template "after all" hook for "should work":
>     Error: the string "no access token supplied" was thrown, throw an Error :)
>      at tryCallOne (node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:37:12)
>      at node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:103:15
>      at flush (node_modules/promisify-node/node_modules/nodegit-promise/node_modules/asap/raw.js:50:29)

Example builds with failing jobs:
- https://travis-ci.org/mozilla/oghliner/builds/90824368
- https://travis-ci.org/mozilla/oghliner/builds/90824646
- https://travis-ci.org/mozilla/oghliner/builds/90825130

**Comment by marco-c** [comment] 2015-11-12 22:24
1 is likely the cause of 2.

I wonder if the failure is due to too many logins to GitHub (I've seen this sometimes).
I haven't noticed when you merged my PRs, but if you merged them shortly one after another, the high number of GitHub logins could have caused the test to fail.

**Comment by mykmelez** [comment] 2015-11-12 23:23
Hmm, interesting. I tried re-running the failing job in https://travis-ci.org/mozilla/oghliner/builds/90824368, and it succeeded, so I guess it's an intermittent failure, perhaps from too many logins. Closing for now, but let's keep an eye on this.

**Comment by mykmelez** [comment] 2015-11-13 01:25
Too frequent, ugh, reopening.

https://travis-ci.org/mozilla/oghliner/builds/90857900
https://travis-ci.org/mozilla/oghliner/builds/90857922

**Comment by marco-c** [comment] 2015-11-13 12:19
I've opened #186 to investigate more. Hopefully using native promises in sw-precache will give us more details about the error.

**Comment by marco-c** [comment] 2015-11-21 14:18
I think the error was related to #215, #222 should fix it.

**Closed as completed** 2015-11-21 18:27 UTC
